image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm ci

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - esbenp.prettier-vscode@6.3.1:iOVHVb01wildbNZ98o51fQ==
